### ISSUE TITLE
Can't install on beast v2.4.7

### ISSUE THREAD

**Issue by MiguelMSandin** [rbouckaert/AlmostDistributions#3]
Dear Remco,
First of all, thanks for all the contributions and help! Amazing job!
I can't install AlmostDistributions ([v0.2.0](https://github.com/rbouckaert/AlmostDistributions/releases/tag/v0.2.0)) on BEAST v2.4.7. Might need an update on '[packages-extra.xml](https://raw.githubusercontent.com/CompEvol/CBAN/master/packages-extra.xml)'?
Thanks in advance.

**Comment by rbouckaert** [comment]
Hi Miguel, the entry is in `packages-extra-2.7.xml` instead of `packages-extra.xml` for v2.7 (I assume v2.4.7 was a typo and meant to be v2.7.4). This was not clear from the README, which still pointed to `package-extra.xml` so I updated that and hope that will fix this issue. Thanks for pointing this out. Cheers, Remco

**Comment by MiguelMSandin** [comment]
Thanks for the fast answer! It's working now :)
(Yes it was a typo, I meant 2.7, thanks for understanding anyways)

Regarding the README update, there is just a typo in the link: just need to delete `/packages-extra.xml` in between `.../master` and `/packages-extra-2.7.xml` and it works
https://raw.githubusercontent.com/CompEvol/CBAN/master/packages-extra-2.7.xml

**Comment by rbouckaert** [comment]
That was a bit careless of me. Thanks for you suggestion! It should be fixed now.
